{% set name = "pystitcher" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/captn3m0/pystitcher/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a1c3f4249175c522fc07779fd577f73d1c11a2056210b8bcfae66440f6adfc79

build:
  number: 0
  noarch: python
  entry_points:
    - pystitcher = pystitcher.skeleton:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - html5lib >=0.0.9
    - importlib-metadata
    - markdown >=3.3.4
    - pypdf3 >=1.0.4
    - python >={{ python_min }}
    - validators >=0.34.0

test:
  imports:
    - pystitcher
  commands:
    - pystitcher --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/captn3m0/pystitcher
  summary: Stitch together a PDF file from multiple sources in a declarative manner
  dev_url: https://github.com/captn3m0/pystitcher
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
